AllCops:
  NewCops: enable
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
http://localhost:9898/Local/Archive%202/9wzdncrfj4mv%20(Joshua%20Osburn's%20conflicted%20copy).dat?FED83E7F-5CE5-408F-A469-DD274CEB76EE